/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedLayoutRouteImport } from './routes/(protected)/layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as authRedefinirSenhaRouteImport } from './routes/(auth)/redefinir-senha'
import { Route as authRecuperarSenhaRouteImport } from './routes/(auth)/recuperar-senha'
import { Route as protectedConfiguracoesLayoutRouteImport } from './routes/(protected)/configuracoes/layout'
import { Route as protectedConfiguracoesSenhaRouteImport } from './routes/(protected)/configuracoes/senha'
import { Route as protectedConfiguracoesPerfilRouteImport } from './routes/(protected)/configuracoes/perfil'
import { Route as protectedConfiguracoesAparenciaRouteImport } from './routes/(protected)/configuracoes/aparencia'

const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLayoutRoute,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const authRedefinirSenhaRoute = authRedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => authLayoutRoute,
} as any)
const authRecuperarSenhaRoute = authRecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => authLayoutRoute,
} as any)
const protectedConfiguracoesLayoutRoute =
  protectedConfiguracoesLayoutRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedConfiguracoesSenhaRoute =
  protectedConfiguracoesSenhaRouteImport.update({
    id: '/senha',
    path: '/senha',
    getParentRoute: () => protectedConfiguracoesLayoutRoute,
  } as any)
const protectedConfiguracoesPerfilRoute =
  protectedConfiguracoesPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => protectedConfiguracoesLayoutRoute,
  } as any)
const protectedConfiguracoesAparenciaRoute =
  protectedConfiguracoesAparenciaRouteImport.update({
    id: '/aparencia',
    path: '/aparencia',
    getParentRoute: () => protectedConfiguracoesLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/configuracoes': typeof protectedConfiguracoesLayoutRouteWithChildren
  '/recuperar-senha': typeof authRecuperarSenhaRoute
  '/redefinir-senha': typeof authRedefinirSenhaRoute
  '/dashboard': typeof protectedDashboardRoute
  '/': typeof authIndexRoute
  '/configuracoes/aparencia': typeof protectedConfiguracoesAparenciaRoute
  '/configuracoes/perfil': typeof protectedConfiguracoesPerfilRoute
  '/configuracoes/senha': typeof protectedConfiguracoesSenhaRoute
}
export interface FileRoutesByTo {
  '/configuracoes': typeof protectedConfiguracoesLayoutRouteWithChildren
  '/recuperar-senha': typeof authRecuperarSenhaRoute
  '/redefinir-senha': typeof authRedefinirSenhaRoute
  '/dashboard': typeof protectedDashboardRoute
  '/': typeof authIndexRoute
  '/configuracoes/aparencia': typeof protectedConfiguracoesAparenciaRoute
  '/configuracoes/perfil': typeof protectedConfiguracoesPerfilRoute
  '/configuracoes/senha': typeof protectedConfiguracoesSenhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(protected)': typeof protectedLayoutRouteWithChildren
  '/(protected)/configuracoes': typeof protectedConfiguracoesLayoutRouteWithChildren
  '/(auth)/recuperar-senha': typeof authRecuperarSenhaRoute
  '/(auth)/redefinir-senha': typeof authRedefinirSenhaRoute
  '/(protected)/dashboard': typeof protectedDashboardRoute
  '/(auth)/': typeof authIndexRoute
  '/(protected)/configuracoes/aparencia': typeof protectedConfiguracoesAparenciaRoute
  '/(protected)/configuracoes/perfil': typeof protectedConfiguracoesPerfilRoute
  '/(protected)/configuracoes/senha': typeof protectedConfiguracoesSenhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/configuracoes'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/dashboard'
    | '/'
    | '/configuracoes/aparencia'
    | '/configuracoes/perfil'
    | '/configuracoes/senha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/configuracoes'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/dashboard'
    | '/'
    | '/configuracoes/aparencia'
    | '/configuracoes/perfil'
    | '/configuracoes/senha'
  id:
    | '__root__'
    | '/(auth)'
    | '/(protected)'
    | '/(protected)/configuracoes'
    | '/(auth)/recuperar-senha'
    | '/(auth)/redefinir-senha'
    | '/(protected)/dashboard'
    | '/(auth)/'
    | '/(protected)/configuracoes/aparencia'
    | '/(protected)/configuracoes/perfil'
    | '/(protected)/configuracoes/senha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(auth)/redefinir-senha': {
      id: '/(auth)/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof authRedefinirSenhaRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/recuperar-senha': {
      id: '/(auth)/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof authRecuperarSenhaRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(protected)/configuracoes': {
      id: '/(protected)/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof protectedConfiguracoesLayoutRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/configuracoes/senha': {
      id: '/(protected)/configuracoes/senha'
      path: '/senha'
      fullPath: '/configuracoes/senha'
      preLoaderRoute: typeof protectedConfiguracoesSenhaRouteImport
      parentRoute: typeof protectedConfiguracoesLayoutRoute
    }
    '/(protected)/configuracoes/perfil': {
      id: '/(protected)/configuracoes/perfil'
      path: '/perfil'
      fullPath: '/configuracoes/perfil'
      preLoaderRoute: typeof protectedConfiguracoesPerfilRouteImport
      parentRoute: typeof protectedConfiguracoesLayoutRoute
    }
    '/(protected)/configuracoes/aparencia': {
      id: '/(protected)/configuracoes/aparencia'
      path: '/aparencia'
      fullPath: '/configuracoes/aparencia'
      preLoaderRoute: typeof protectedConfiguracoesAparenciaRouteImport
      parentRoute: typeof protectedConfiguracoesLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authRecuperarSenhaRoute: typeof authRecuperarSenhaRoute
  authRedefinirSenhaRoute: typeof authRedefinirSenhaRoute
  authIndexRoute: typeof authIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authRecuperarSenhaRoute: authRecuperarSenhaRoute,
  authRedefinirSenhaRoute: authRedefinirSenhaRoute,
  authIndexRoute: authIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface protectedConfiguracoesLayoutRouteChildren {
  protectedConfiguracoesAparenciaRoute: typeof protectedConfiguracoesAparenciaRoute
  protectedConfiguracoesPerfilRoute: typeof protectedConfiguracoesPerfilRoute
  protectedConfiguracoesSenhaRoute: typeof protectedConfiguracoesSenhaRoute
}

const protectedConfiguracoesLayoutRouteChildren: protectedConfiguracoesLayoutRouteChildren =
  {
    protectedConfiguracoesAparenciaRoute: protectedConfiguracoesAparenciaRoute,
    protectedConfiguracoesPerfilRoute: protectedConfiguracoesPerfilRoute,
    protectedConfiguracoesSenhaRoute: protectedConfiguracoesSenhaRoute,
  }

const protectedConfiguracoesLayoutRouteWithChildren =
  protectedConfiguracoesLayoutRoute._addFileChildren(
    protectedConfiguracoesLayoutRouteChildren,
  )

interface protectedLayoutRouteChildren {
  protectedConfiguracoesLayoutRoute: typeof protectedConfiguracoesLayoutRouteWithChildren
  protectedDashboardRoute: typeof protectedDashboardRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedConfiguracoesLayoutRoute:
    protectedConfiguracoesLayoutRouteWithChildren,
  protectedDashboardRoute: protectedDashboardRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
